name: apt
inputs:
  withSudo:
    default: true
    required: false
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        set -x

        export DEBIAN_FRONTEND=noninteractive
        ${{ inputs.withSudo == 'true' && 'sudo' || '' }} apt-get update -y | true
        ${{ inputs.withSudo == 'true' && 'sudo' || '' }} apt-get install -y \
          autoconf \
          gcc \
          make \
          bison \
          re2c \
          git \
          curl \
          locales \
          ldap-utils \
          openssl \
          slapd \
          language-pack-de \
          libgmp-dev \
          libicu-dev \
          libtidy-dev \
          libenchant-2-dev \
          libaspell-dev \
          libbz2-dev \
          libpspell-dev \
          libsasl2-dev \
          libxpm-dev \
          libzip-dev \
          libsqlite3-dev \
          libwebp-dev \
          libonig-dev \
          libkrb5-dev \
          libgssapi-krb5-2 \
          libcurl4-openssl-dev \
          libxml2-dev \
          libxslt1-dev \
          libpq-dev \
          libreadline-dev \
          libldap2-dev \
          libsodium-dev \
          libargon2-0-dev \
          libmm-dev \
          libsnmp-dev \
          postgresql \
          postgresql-contrib \
          snmpd \
          snmp-mibs-downloader \
          freetds-dev \
          unixodbc-dev \
          llvm \
          clang \
          libc-client-dev \
          dovecot-core \
          dovecot-pop3d \
          dovecot-imapd \
          sendmail \
          firebird-dev \
          liblmdb-dev \
          libtokyocabinet-dev \
          libdb-dev \
          libqdbm-dev \
          libjpeg-dev \
          libpng-dev \
          libfreetype6-dev \
          unzip
