name: ./configure
inputs:
  configurationParameters:
    default: ''
    required: false
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        if [ "$ARCH" == "linux-x64" ]; then
          ./buildconf --force
          ./configure \
            --enable-option-checking=fatal \
            --prefix=/usr \
            --enable-phpdbg \
            --enable-fpm \
            --with-pdo-mysql=mysqlnd \
            --with-mysqli=mysqlnd \
            --with-pgsql \
            --with-pdo-pgsql \
            --with-pdo-sqlite \
            --enable-intl \
            --without-pear \
            --enable-gd \
            --with-jpeg \
            --with-webp \
            --with-freetype \
            --with-xpm \
            --enable-exif \
            --with-zip \
            --with-zlib \
            --with-zlib-dir=/usr \
            --enable-soap \
            --enable-xmlreader \
            --with-xsl \
            --with-tidy \
            --enable-sysvsem \
            --enable-sysvshm \
            --enable-shmop \
            --enable-pcntl \
            --with-readline \
            --enable-mbstring \
            --with-curl \
            --with-gettext \
            --enable-sockets \
            --with-bz2 \
            --with-openssl \
            --with-gmp \
            --enable-bcmath \
            --enable-calendar \
            --enable-ftp \
            --with-pspell=/usr \
            --with-enchant=/usr \
            --with-kerberos \
            --enable-sysvmsg \
            --with-ffi \
            --enable-zend-test \
            --with-ldap \
            --with-ldap-sasl \
            --with-password-argon2 \
            --with-mhash \
            --with-sodium \
            --enable-dba \
            --with-cdb \
            --enable-flatfile \
            --enable-inifile \
            --with-tcadb \
            --with-lmdb \
            --with-qdbm \
            --with-snmp \
            --with-unixODBC \
            --with-imap \
            --with-kerberos \
            --with-imap-ssl \
            --with-pdo-odbc=unixODBC,/usr \
            --with-pdo-firebird \
            --with-pdo-dblib \
            --with-pdo-oci=shared,instantclient,/opt/oracle/instantclient \
            --with-oci8=shared,instantclient,/opt/oracle/instantclient \
            --enable-werror \
            --with-config-file-path=/etc \
            --with-config-file-scan-dir=/etc/php.d \
            ${{ inputs.configurationParameters }}
        fi
        if [ "$ARCH" == "linux-i386" ]; then
          ./buildconf --force
          export CFLAGS="-m32 -msse2"
          export CXXFLAGS="-m32 -msse2"
          export LDFLAGS=-L/usr/lib/i386-linux-gnu
          export PKG_CONFIG=/usr/bin/i686-linux-gnu-pkg-config
          ./configure \
            --enable-option-checking=fatal \
            --build=i686-pc-linux-gnu \
            --prefix=/usr \
            --enable-phpdbg \
            --enable-fpm \
            --enable-intl \
            --with-pdo-mysql=mysqlnd \
            --with-mysqli=mysqlnd \
            --with-pgsql \
            --with-pdo-pgsql \
            --with-pdo-sqlite \
            --without-pear \
            --enable-gd \
            --with-jpeg \
            --with-webp \
            --with-freetype \
            --with-xpm \
            --enable-exif \
            --with-zip \
            --with-zlib \
            --with-zlib-dir=/usr \
            --enable-soap \
            --enable-xmlreader \
            --with-xsl \
            --with-tidy \
            --enable-sysvsem \
            --enable-sysvshm \
            --enable-shmop \
            --enable-pcntl \
            --with-readline \
            --enable-mbstring \
            --with-curl \
            --with-gettext \
            --enable-sockets \
            --with-bz2 \
            --with-openssl \
            --with-gmp \
            --enable-bcmath \
            --enable-calendar \
            --enable-ftp \
            --with-pspell=/usr \
            --with-kerberos \
            --enable-sysvmsg \
            --with-ffi \
            --enable-zend-test \
            --with-mhash \
            --with-sodium \
            --enable-dba \
            --enable-werror \
            --with-config-file-path=/etc \
            --with-config-file-scan-dir=/etc/php.d \
            ${{ inputs.configurationParameters }}
        fi
        if [ "$ARCH" == "macos" ]; then
          export PATH="/usr/local/opt/bison/bin:$PATH"
          export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/local/opt/openssl@1.1/lib/pkgconfig"
          export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/local/opt/krb5/lib/pkgconfig"
          export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/local/opt/libffi/lib/pkgconfig"
          export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/local/opt/libxml2/lib/pkgconfig"
          export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/local/opt/libxslt/lib/pkgconfig"
          export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/local/opt/zlib/lib/pkgconfig"
          export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/local/opt/icu4c/lib/pkgconfig"
          ./buildconf --force
          ./configure \
            --enable-option-checking=fatal \
            --prefix=/usr/local \
            --enable-fpm \
            --with-pdo-mysql=mysqlnd \
            --with-mysqli=mysqlnd \
            --with-pgsql=/usr/local/opt/libpq \
            --with-pdo-pgsql=/usr/local/opt/libpq \
            --with-pdo-sqlite \
            --without-pear \
            --enable-gd \
            --with-jpeg \
            --with-webp \
            --with-freetype \
            --enable-exif \
            --with-zip \
            --with-zlib \
            --enable-soap \
            --enable-xmlreader \
            --with-xsl \
            --with-tidy=/usr/local/opt/tidyp \
            --with-libxml \
            --enable-sysvsem \
            --enable-sysvshm \
            --enable-shmop \
            --enable-pcntl \
            --with-readline=/usr/local/opt/readline \
            --enable-mbstring \
            --with-curl \
            --with-gettext=/usr/local/opt/gettext \
            --enable-sockets \
            --with-bz2=/usr/local/opt/bzip2 \
            --with-openssl \
            --with-gmp=/usr/local/opt/gmp \
            --with-iconv=/usr/local/opt/libiconv \
            --enable-bcmath \
            --enable-calendar \
            --enable-ftp \
            --with-pspell=/usr/local/opt/aspell \
            --with-kerberos \
            --enable-sysvmsg \
            --with-ffi \
            --enable-zend-test \
            --enable-intl \
            --with-mhash \
            --with-sodium \
            --enable-dba \
            --enable-werror \
            --with-config-file-path=/etc \
            --with-config-file-scan-dir=/etc/php.d \
            ${{ inputs.configurationParameters }}
        fi
