name: Linux x64
inputs:
  configurationParameters:
    required: true
  extendedTests:
    required: true
runs:
  using: composite
  steps:
    - name: git checkout
      uses: actions/checkout@v2
    - name: Create mssql container
      uses: ./.github/actions/mssql
    - name: apt
      uses: ./.github/actions/apt-x64
    - name: ./configure
      uses: ./.github/actions/configure-x64
      with:
        configurationParameters: ${{ inputs.configurationParameters }}
    - name: make
      shell: bash
      run: make -j$(/usr/bin/nproc) >/dev/null
    - name: make install
      uses: ./.github/actions/install-linux
    - name: Setup
      uses: ./.github/actions/setup-x64
    - name: Test
      uses: ./.github/actions/tests-linux
      with:
        extended: ${{ inputs.extendedTests }}
