name: Setup Caddy server
inputs:
  withSudo:
    default: true
    required: false
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        set -x
        ${{ inputs.withSudo == 'true' && 'sudo' || '' }} curl 'https://caddyserver.com/api/download?os=linux&arch=amd64' -o /usr/bin/caddy
        ${{ inputs.withSudo == 'true' && 'sudo' || '' }} chmod +x /usr/bin/caddy
        ${{ inputs.withSudo == 'true' && 'sudo' || '' }} caddy start --config ext/curl/tests/Caddyfile
