name: Nightly
# Update to only run on a schedule
on:
  push:
    ignore-paths:
    - docs/*
    - NEWS
    - UPGRADING
    - UPGRADING.INTERNALS
    - README.md
    - CONTRIBUTING.md
    - CODING_STANDARDS.md
jobs:
  generate-matrix:
    name: Generate Build Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate Build Matrix
        id: set-matrix
        run: php .github/nightly_matrix.php
  test:
    needs: generate-matrix
    strategy:
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
      fail-fast: false
    name: ${{ matrix.name }}
    runs-on: ${{ startsWith(matrix['arch'], 'linux-') && 'ubuntu-20.04' || 'macOS-10.15' }}
    env:
      ARCH: ${{ matrix.arch }}
    steps:
      - name: git checkout
        uses: actions/checkout@v2
        # Only test on current branch until merged
        # with:
        #   ref: ${{ matrix.branch }}
      - name: Create mssql container
        if: ${{ env.ARCH != 'macos' }}
        uses: ./.github/actions/mssql
      - name: Install dependencies
        uses: ./.github/actions/deps
      - name: ./configure
        uses: ./.github/actions/configure
        with:
          configurationParameters: ${{ matrix.configurationParameters }}
      - name: make
        shell: bash
        run: |
          if [ "$ARCH" == "macos" ]; then
            export PATH="/usr/local/opt/bison/bin:$PATH"
          fi
          make -j$(${{ env.ARCH != 'macos' && '/usr/bin/nproc' || 'sysctl -n hw.logicalcpu' }}) >/dev/null
      - name: make install
        uses: ./.github/actions/install
      - name: Setup
        if: ${{ env.ARCH != 'macos' }}
        uses: ./.github/actions/setup
      - name: Test
        uses: ./.github/actions/tests
        with:
          extended: ${{ inputs.extendedTests }}
