name: Push
on:
  push:
    ignore-paths:
    - docs/*
    - NEWS
    - UPGRADING
    - UPGRADING.INTERNALS
    - README.md
    - CONTRIBUTING.md
    - CODING_STANDARDS.md
jobs:
  test:
    strategy:
      matrix:
        include:
          - name: LINUX_X64_DEBUG_NTS
            action: linux-x64
            configurationParameters: --enable-debug --disable-zts
          - name: LINUX_X64_RELEASE_ZTS
            action: linux-x64
            configurationParameters: --disable-debug --enable-zts
          # apt broken, not sure why
          # - name: LINUX_I386_DEBUG_ZTS
          #   action: linux-i386
          #   configurationParameters: --enable-debug --disable-zts
          - name: MACOS_DEBUG_NTS
            action: macos
            configurationParameters: --enable-debug --disable-zts
      fail-fast: false
    name: ${{ matrix.name }}
    runs-on: ${{ matrix['runs-on'] }}
    steps:
      - uses: ${{ matrix.action }}
        with:
          configurationParameters: ${{ matrix.configurationParameters }}
          extendedTests: false
